apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe-config
  namespace: default
data:
  application.yaml: |
    zeebe:
      client:
        broker:
          gateway-address: 127.0.0.1:26500
        security:
          plaintext: true
      broker:
        exporters:
          customExporter:
            className: com.isu.camunda.exporter.process.CustomPostgresExporter
            jarPath: /usr/local/zeebe/exporters/camunda-exporter-0.0.1-SNAPSHOT.jar
            args:
              jdbcUrl: jdbc:postgresql://35.200.195.169:5432/bitnami_keycloak
              username: bn_keycloak
              password: #3]O?4RGj)DE7Z!9SA5
            bulk:
              delay: 5
              size: 1000
            col:
              prefix: zeebe-record
              createCollections: true
              command: false
              event: true
              rejection: false
              deployment: true
              error: true
              incident: true
              job: true
              jobBatch: false
              message: true
              messageSubscription: true
              variable: true
              variableDocument: true
              workflowInstance: true
              workflowInstanceCreation: false
              workflowInstanceSubscription: false
              timers: true
