apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic
  namespace: gloo-system
  # labels:
    # app: kc
    # app.kubernetes.io/name: camunda-platform
    # app.kubernetes.io/instance: camunda
    # app.kubernetes.io/managed-by: Helm
    # app.kubernetes.io/part-of: camunda-platform
    # helm.sh/chart: camunda-platform-11.0.4
  # annotations: 
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    # nginx.ingress.kubernetes.io/proxy-buffering: "on"
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/backend-protocol: "http"
spec:
  ingressClassName: nginx
  rules:
    - host: txnflow.txninfra.com
      http:
        paths:
          # - path: /isu/camunda/
          #   backend:
          #     service:
          #       name: redirect-app
          #       # namespace: gateway
          #       port:
          #         number: 80
          #   pathType: Prefix
          - backend:
              service:
                name: gateway-proxy	
                # namespace: gateway
                port:
                  number: 80
            path: /elasticsearch
            pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-operate
          #       port:
          #         number: 80
          #   path: /operate
          #   pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-optimize
          #       port:
          #         number: 80
          #   path: /optimize
          #   pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-tasklist
          #       port:
          #         number: 80
          #   path: /tasklist
          #   pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-connectors
          #       port:
          #         number: 8080
          #   path: /connectors
          #   pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-zeebe-gateway
          #       port:
          #         number: 9600
          #   path: /zeebe
          #   pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-zeebe-gateway
          #       port:
          #         number: 8080
          #   path: /zeebbe
          #   pathType: Prefix
          # - backend:
          #     service:
          #       name: camunda-zeebe
          #       port:
          #         number: 9600
          #   path: /v2
          #   pathType: Prefix
          
          
      