apiVersion: v1
kind: Secret
metadata:
  name: identity-secret-for-components
type: Opaque
data:
  identity-secret: Y2FtdW5kYS1zZWNyZXQK
  operate-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for operate-secret
  tasklist-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for tasklist-secret
  optimize-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for optimize-secret
  connectors-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for connectors-secret
  console-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for console-secret
  keycloak-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for keycloak-secret
  zeebe-secret: Y2FtdW5kYS1zZWNyZXQK # Base64-encoded value for zeebe-secret
  admin-password: Y2FtdW5kYS1zZWNyZXQK
  # postgres-password: cGFzc3dvcmQxMjM= # Base64-encoded PostgreSQL password (e.g. 'password123')
  # postgres-user: cG9zdGdyZXM=  # Base64-encoded PostgreSQL user (e.g. 'postgres')
  # postgres-database: Y2FtdW5kYQ== # Base64-encoded PostgreSQL database name (e.g. 'camunda')
  # password: cG9zdGdyZXM=
  # management-password: YWRtaW4=

#echo -n 'password123' | base64